# Prometheus configuration for Guanacaste Real Estate Platform
# Production-ready monitoring with service discovery and alerting

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Add alertmanager targets here when needed

scrape_configs:
  # Application metrics
  - job_name: 'guanacaste-web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/api/health/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'web'
      - source_labels: [__address__]
        target_label: job
        replacement: 'guanacaste-web'

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-host'

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nginx'

  # PostgreSQL Exporter (Supabase)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 60s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'supabase-postgres'

  # Pushgateway for batch jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Loki (for log aggregation)
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 60s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'loki'